---
deployment:
  tasks:
    - export DEPLOYPATH=//home/amelkyau/ind-checker.ameliamargaurite.dev
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R biometrics $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R documents $DEPLOYPATH
    - /bin/cp -R endorsement-sticker $DEPLOYPATH
    - /bin/cp -R imgs $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R return-visa $DEPLOYPATH
